export interface Race {
  id?: string; // Auto-generated by Firebase
  name: string;
  description: string;
  schedule: string;
  track_details: string;
  created_by: string; // User ID of the creator
}
